# Generated by Django 2.0.1 on 2018-11-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_create_initial_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='report',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
