# Generated by Django 2.0.1 on 2018-11-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20181101_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='report',
        ),
    ]
