# Generated by Django 2.0.1 on 2018-11-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20181101_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='report',
            field=models.FileField(upload_to=''),
        ),
    ]
