# Generated by Django 2.0.1 on 2018-11-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_quiz_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='report',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
