# Generated by Django 2.0.1 on 2018-11-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_auto_20181101_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_head',
            field=models.BooleanField(default=False),
        ),
    ]
